export const GET_ERRORS = 'GET_ERRORS';
export const GET_PROJECTS = 'GET_PROJECTS';
export const CREATE_FOLDER = 'CREATE_FOLDER';
export const GET_ALL_FOLDERS = 'GET_ALL_FOLDERS';
export const GET_ALL_FROM_FOLDER = 'GET_ALL_FROM_FOLDER';
export const CREATE_PROJECT = 'CREATE_PROJECT';
export const DELETE_FILE = 'DELETE_FILE';
export const CHANGE_TEXT_AUDIO_SENTENCE = 'CHANGE_TEXT_AUDIO_SENTENCE';
export const CHANGE_TEXT_AUDIO_LOAD_THROUGH = 'CHANGE_TEXT_AUDIO_LOAD_THROUGH';
export const AUTH_USER = 'LOG_IN_USER';
export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';
export const LOG_OUT = 'LOG_OUT';
export const SET_FAV_FOLDER = 'SET_FAV_FOLDER';
export const GET_ALL_FROM_GOLDER_USER_ACCESS =
  'GET_ALL_FROM_GOLDER_USER_ACCESS';
export const CHANGE_DISPLAY_STATUS = 'CHANGE_DISPLAY_STATUS';
export const SAVE_TO_USER_REPEAT_COLLECTION = 'SAVE_TO_USER_REPEAT_COLLECTION';
export const GET_ALL_FROM_USER_LEARNING_COLLECTION =
  'GET_ALL_FROM_USER_LEARNING_COLLECTION';
export const SET_CUSTOM_LEARNING_UNITS = 'SET_CUSTOM_LEARNING_UNITS';
export const SET_FAV_LEARNING_UNIT = 'SET_FAV_LEARNING_UNIT';
export const SELECT_FOR_REPEAT_ITEM = 'SELECT_FOR_REPEAT_ITEM';
export const START_REPEAT_FROM_SELECTED_FOR_REPEAT =
  'START_REPEAT_FROM_SELECTED_FOR_REPEAT';
export const DELETE_FROM_USER_LEARNING_LIST = 'DELETE_FROM_USER_LEARNING_LIST';
export const REPEAT_ALL_FROM_USER_REPEAT_LIST =
  'REPEAT_ALL_FROM_USER_REPEAT_LIST';
export const REPEAT_FAVORITE_USER_WORDS = 'REPEAT_FAVORITE_USER_WORDS';
export const LOAD_IMAGE_FOLDER = 'LOAD_IMAGE_FOLDER';
export const DELETE_FOLDER = 'DELETE_FOLDER';
